export const sushiMenu = [
  {
    id: "california-roll",
    name: "California Roll",
    description: "Rollo clasico con surimi, aguacate y pepino, ideal para empezar.",
    price: 129,
    ingredients: ["surimi", "aguacate", "pepino", "arroz", "alga nori", "ajonjoli"],
    extras: [
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
      { id: "topping-anguila", name: "topping de anguila", price: 28 },
    ],
  },
  {
    id: "philadelphia-roll",
    name: "Philadelphia Roll",
    description: "Rollo cremoso con salmon fresco, queso crema y pepino.",
    price: 149,
    ingredients: ["salmon", "queso crema", "pepino", "arroz", "alga nori"],
    extras: [
      { id: "extra-salmon", name: "extra salmon", price: 30 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-soya-dulce", name: "salsa de anguila", price: 22 },
    ],
  },
  {
    id: "spicy-tuna",
    name: "Spicy Tuna",
    description: "Rollo con atun sazonado con mayo picante y toque de cebollin.",
    price: 158,
    ingredients: ["tuna", "mayonesa picante", "cebollin", "pepino", "arroz", "alga nori"],
    extras: [
      { id: "extra-atun", name: "extra atun", price: 32 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "ajonjoli-tostado", name: "ajonjoli tostado", price: 10 },
    ],
  },
  {
    id: "tempura-roll",
    name: "Tempura Roll",
    description: "Rollo empanizado y crujiente con camaron, aguacate y queso crema.",
    price: 165,
    ingredients: ["shrimp tempura", "aguacate", "queso crema", "arroz", "alga nori", "panko"],
    extras: [
      { id: "extra-camaron", name: "extra camaron tempura", price: 30 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-chipotle", name: "salsa chipotle", price: 15 },
      { id: "topping-anguila", name: "topping de anguila", price: 28 },
    ],
  },
  {
    id: "dragon-roll",
    name: "Dragon Roll",
    description: "Rollo de camaron tempura cubierto con laminas de aguacate y salsa de anguila.",
    price: 189,
    ingredients: ["shrimp tempura", "aguacate", "pepino", "arroz", "alga nori", "salsa de anguila"],
    extras: [
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "topping-anguila", name: "topping de anguila", price: 28 },
      { id: "extra-camaron", name: "extra camaron tempura", price: 30 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
    ],
  },
  {
    id: "rainbow-roll",
    name: "Rainbow Roll",
    description: "California cubierto con salmon, atun y aguacate para un sabor variado.",
    price: 198,
    ingredients: ["surimi", "salmon", "tuna", "aguacate", "pepino", "arroz", "alga nori"],
    extras: [
      { id: "extra-salmon", name: "extra salmon", price: 30 },
      { id: "extra-atun", name: "extra atun", price: 32 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "topping-ajonjoli", name: "ajonjoli mixto", price: 10 },
    ],
  },
  {
    id: "ebi-roll",
    name: "Ebi Roll",
    description: "Rollo fresco con camaron cocido, pepino y un toque de queso crema.",
    price: 152,
    ingredients: ["camaron", "pepino", "queso crema", "aguacate", "arroz", "alga nori"],
    extras: [
      { id: "extra-camaron", name: "extra camaron", price: 28 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
    ],
  },
  {
    id: "mango-roll",
    name: "Mango Roll",
    description: "Rollo tropical con mango, salmon y queso crema, ligeramente dulce.",
    price: 176,
    ingredients: ["mango", "salmon", "queso crema", "pepino", "arroz", "alga nori"],
    extras: [
      { id: "extra-mango", name: "extra mango", price: 18 },
      { id: "extra-salmon", name: "extra salmon", price: 30 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-anguila", name: "salsa de anguila", price: 22 },
    ],
  },
  {
    id: "mar-y-tierra-roll",
    name: "Mar y Tierra Roll",
    description: "Combinacion de arrachera y camaron con aguacate y aderezo especial.",
    price: 185,
    ingredients: ["arrachera", "camaron", "aguacate", "pepino", "arroz", "alga nori"],
    extras: [
      { id: "extra-arrachera", name: "extra arrachera", price: 30 },
      { id: "extra-camaron", name: "extra camaron", price: 28 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "salsa-chipotle", name: "salsa chipotle", price: 15 },
    ],
  },
  {
    id: "tampico-roll",
    name: "Tampico Roll",
    description: "Rollo coronado con ensalada tampico, suave y muy popular.",
    price: 172,
    ingredients: ["surimi", "tampico", "aguacate", "pepino", "arroz", "alga nori"],
    extras: [
      { id: "extra-tampico", name: "extra tampico", price: 25 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
    ],
  },
  {
    id: "yakimeshi-roll",
    name: "Yakimeshi Roll",
    description: "Rollo relleno de pollo empanizado con un toque de arroz frito estilo casa.",
    price: 168,
    ingredients: ["pollo empanizado", "aguacate", "queso crema", "zanahoria", "arroz", "alga nori"],
    extras: [
      { id: "extra-pollo", name: "extra pollo", price: 25 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-teriyaki", name: "salsa teriyaki", price: 15 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
    ],
  },
  {
    id: "kani-crunch-roll",
    name: "Kani Crunch Roll",
    description: "Rollo de surimi con topping crujiente y aderezo spicy.",
    price: 144,
    ingredients: ["surimi", "pepino", "aguacate", "arroz", "alga nori", "crunch tempura"],
    extras: [
      { id: "extra-surimi", name: "extra surimi", price: 20 },
      { id: "crunch-extra", name: "crunch extra", price: 12 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
    ],
  },
  {
    id: "salmon-skin-roll",
    name: "Salmon Skin Roll",
    description: "Rollo con piel de salmon crujiente, pepino y salsa ligera.",
    price: 162,
    ingredients: ["piel de salmon", "pepino", "aguacate", "arroz", "alga nori", "ajonjoli"],
    extras: [
      { id: "extra-salmon", name: "extra salmon", price: 30 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "salsa-anguila", name: "salsa de anguila", price: 22 },
      { id: "crunch-extra", name: "crunch extra", price: 12 },
    ],
  },
  {
    id: "atun-spicy-mango-roll",
    name: "Atun Spicy Mango Roll",
    description: "Atun picante con mango fresco para un balance entre picor y dulzor.",
    price: 184,
    ingredients: ["tuna", "mango", "aguacate", "pepino", "mayonesa picante", "arroz", "alga nori"],
    extras: [
      { id: "extra-atun", name: "extra atun", price: 32 },
      { id: "extra-mango", name: "extra mango", price: 18 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
    ],
  },
  {
    id: "cielo-mar-tierra-roll",
    name: "Cielo Mar y Tierra Roll",
    description: "Rollo abundante con pollo, res y camaron, favorito para compartir.",
    price: 210,
    ingredients: ["pollo", "res", "camaron", "aguacate", "queso crema", "arroz", "alga nori"],
    extras: [
      { id: "extra-res", name: "extra res", price: 30 },
      { id: "extra-camaron", name: "extra camaron", price: 28 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-chipotle", name: "salsa chipotle", price: 15 },
    ],
  },
  {
    id: "veggie-roll",
    name: "Veggie Roll",
    description: "Opcion vegetariana con vegetales frescos y queso crema.",
    price: 120,
    ingredients: ["aguacate", "pepino", "zanahoria", "queso crema", "esparrago", "arroz", "alga nori"],
    extras: [
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
      { id: "tempura-verduras", name: "tempura de verduras", price: 24 },
    ],
  },
  {
    id: "tori-roll",
    name: "Tori Roll",
    description: "Rollo de pollo a la plancha con aguacate, pepino y salsa teriyaki.",
    price: 138,
    ingredients: ["pollo", "aguacate", "pepino", "arroz", "alga nori", "salsa teriyaki"],
    extras: [
      { id: "extra-pollo", name: "extra pollo", price: 25 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-teriyaki", name: "salsa teriyaki", price: 15 },
    ],
  },
  {
    id: "avocado-salmon-roll",
    name: "Avocado Salmon Roll",
    description: "Rollo sencillo y fresco con salmon y abundante aguacate.",
    price: 174,
    ingredients: ["salmon", "aguacate", "pepino", "arroz", "alga nori", "ajonjoli negro"],
    extras: [
      { id: "extra-salmon", name: "extra salmon", price: 30 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "salsa-anguila", name: "salsa de anguila", price: 22 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
    ],
  },
  {
    id: "ebi-tempura-roll",
    name: "Ebi Tempura Roll",
    description: "Camaron tempura con queso crema y pepino en un rollo dorado y crujiente.",
    price: 188,
    ingredients: ["shrimp tempura", "queso crema", "pepino", "aguacate", "arroz", "alga nori", "panko"],
    extras: [
      { id: "extra-camaron", name: "extra camaron tempura", price: 30 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "topping-anguila", name: "topping de anguila", price: 28 },
      { id: "salsa-chipotle", name: "salsa chipotle", price: 15 },
    ],
  },
  {
    id: "hot-roll-mixto",
    name: "Hot Roll Mixto",
    description: "Rollo empanizado con salmon, surimi y queso crema, muy rendidor.",
    price: 179,
    ingredients: ["salmon", "surimi", "queso crema", "aguacate", "arroz", "alga nori", "panko"],
    extras: [
      { id: "extra-salmon", name: "extra salmon", price: 30 },
      { id: "extra-surimi", name: "extra surimi", price: 20 },
      { id: "extra-queso-crema", name: "extra queso crema", price: 18 },
      { id: "salsa-anguila", name: "salsa de anguila", price: 22 },
    ],
  },
  {
    id: "tropical-roll",
    name: "Tropical Roll",
    description: "Rollo con camaron, mango y aguacate, fresco y perfecto para dias calurosos.",
    price: 171,
    ingredients: ["camaron", "mango", "aguacate", "pepino", "arroz", "alga nori"],
    extras: [
      { id: "extra-camaron", name: "extra camaron", price: 28 },
      { id: "extra-mango", name: "extra mango", price: 18 },
      { id: "extra-aguacate", name: "extra aguacate", price: 20 },
      { id: "salsa-picante", name: "salsa picante", price: 15 },
    ],
  },
];
